### ISSUE TITLE
Questionable mixins?

### ISSUE THREAD

**Issue by slava110** [OpenlyFay/AncientGateways#7]
Hi. What are this mixins used for? :I
[PlayerEntityMixin](https://github.com/OpenlyFay/AncientGateways/blob/e39142b8879e8325638210e318a1dd7f993ed285/src/main/java/openlyfay/ancientgateways/mixins/common/PlayerEntityMixin.java)
[LootableContainerBlockEntityMixin](https://github.com/OpenlyFay/AncientGateways/blob/e39142b8879e8325638210e318a1dd7f993ed285/src/main/java/openlyfay/ancientgateways/mixins/common/LootableContainerBlockEntityMixin.java)

**Comment by OpenlyFay** [comment]
PlayerEntityMixin is there to solve desyncs caused by server-side dismounting not being respected because the player is still mounted on the client side

LootableContainerBlockEntityMixin allows opening chests from any distance while using a certain item (although I'm not super happy with it and I'm probably going to be removing that item and everything associated with it soon)
